# Data paths
data_dir: "/home/krkavinda/Datasets/KITTI_raw/kitti_data/scan"
calib_dir: "/home/krkavinda/Datasets/KITTI_raw/kitti_data/calib"
pose_dir: "/home/krkavinda/Datasets/KITTI_raw/kitti_data/poses"
sequences:
  train: ["00", "02", "08", "09"]
  val: ["03", "04", "05", "06", "07", "10"]
  test: ["01"]

# Subdirectories for modalities
modalities:
  left_rgb: "image_02"
  right_rgb: "image_03"
  depth: "depth"
  velodyne: "velodyne"

# Model hyperparameters
seq_len: 5
img_height: 184
img_width: 608
hidden_size: 1000
cnn_backbone: "resnet18"

# Training hyperparameters
batch_size: 16          # Moved from hardcoded to config
num_workers: 24         # Added for DataLoader
epochs: 50
learning_rate: 0.0001
weight_decay: 0.0001

# Logging and saving
log_project: "FusionLIVO"
model_save_path: "stereo_deepvo.pth"
pose_save_dir: "pred_poses"
plot_save_dir: "plots"