_wandb:
    value:
        cli_version: 0.19.8
        m: []
        python_version: 3.8.10
        t:
            "1":
                - 1
                - 41
                - 55
            "2":
                - 1
                - 41
                - 55
            "3":
                - 16
                - 23
                - 55
            "4": 3.8.10
            "5": 0.19.8
            "8":
                - 5
            "12": 0.19.8
            "13": linux-x86_64
batch_size:
    value: 32
calib_dir:
    value: /home/krkavinda/Datasets/KITTI_raw/kitti_data/calib
cnn_backbone:
    value: resnet18
data_dir:
    value: /home/krkavinda/Datasets/KITTI_raw/kitti_data/scan
epochs:
    value: 5
hidden_size:
    value: 1000
img_height:
    value: 184
img_width:
    value: 608
learning_rate:
    value: 0.0001
log_project:
    value: FusionLIVO
modalities:
    value:
        depth: depth
        left_rgb: image_02
        right_rgb: image_03
        velodyne: velodyne
model_save_path:
    value: stereo_deepvo.pth
num_workers:
    value: 24
plot_save_dir:
    value: plots
pose_dir:
    value: /home/krkavinda/Datasets/KITTI_raw/kitti_data/poses
pose_save_dir:
    value: pred_poses
seq_len:
    value: 10
sequences:
    value:
        test:
            - "01"
        train:
            - "00"
            - "02"
            - "08"
            - "09"
        val:
            - "03"
            - "04"
            - "05"
            - "06"
            - "07"
            - "10"
weight_decay:
    value: 0.0001
